# Generated by Django 4.0.6 on 2024-04-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
