# Generated by Django 5.0.4 on 2024-07-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sliderimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
