# Generated by Django 4.0.6 on 2024-06-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
