# Generated by Django 4.0.6 on 2024-06-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_servicespage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicespage',
            options={},
        ),
    ]
