# Generated by Django 5.0.4 on 2024-07-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userprofile_user_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username_tg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
