# Generated by Django 4.0.6 on 2024-06-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_servicespage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('position', models.CharField(choices=[('top', 'Верхний'), ('bottom', 'Нижний')], max_length=6)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
