# Generated by Django 4.0.6 on 2024-06-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
