# Generated by Django 4.0.6 on 2024-06-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bnr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('position', models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
