# Generated by Django 5.0.4 on 2024-04-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_id', models.IntegerField()),
                ('car_brand', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('car_year', models.IntegerField()),
                ('car_body_type', models.CharField(max_length=255)),
                ('car_engine_type', models.CharField(max_length=255)),
                ('car_engine_volume', models.CharField(max_length=255)),
                ('car_power', models.CharField(max_length=255)),
                ('car_transmission_type', models.CharField(max_length=255)),
                ('car_color', models.CharField(max_length=255)),
                ('car_mileage', models.FloatField()),
                ('car_document_status', models.CharField(max_length=255)),
                ('car_owners', models.IntegerField()),
                ('car_customs_cleared', models.BooleanField()),
                ('car_condition', models.CharField(max_length=255)),
                ('car_description', models.TextField()),
                ('currency', models.CharField(max_length=255)),
                ('car_price', models.FloatField()),
                ('car_location', models.CharField(max_length=255)),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_phone', models.CharField(max_length=20)),
                ('username', models.CharField(default='по номеру телефона', max_length=255)),
                ('photo_url', models.URLField()),
            ],
        ),
    ]
