# Generated by Django 4.0.6 on 2024-05-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carad',
            name='car_currency',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='car_description',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='car_phone',
        ),
        migrations.RemoveField(
            model_name='jobad',
            name='job_contacts',
        ),
        migrations.RemoveField(
            model_name='jobad',
            name='job_currency',
        ),
        migrations.RemoveField(
            model_name='jobad',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='jobad',
            name='job_name',
        ),
        migrations.RemoveField(
            model_name='jobad',
            name='job_price',
        ),
        migrations.RemoveField(
            model_name='realtyad',
            name='realty_currency',
        ),
        migrations.RemoveField(
            model_name='realtyad',
            name='realty_name',
        ),
        migrations.RemoveField(
            model_name='realtyad',
            name='realty_phone',
        ),
        migrations.RemoveField(
            model_name='realtyad',
            name='realty_price',
        ),
    ]
