# Generated by Django 5.0.4 on 2024-04-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='photo_url',
            new_name='sent_photos',
        ),
    ]
