# Generated by Django 5.0.4 on 2024-07-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='car_body_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_customs_cleared',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_document_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_engine_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_engine_volume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_mileage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_owners',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_power',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_transmission_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
