# Generated by Django 4.0.6 on 2024-04-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carad',
            name='ad_id',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='description',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='price',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='title',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='user',
        ),
    ]
