# Generated by Django 4.0.6 on 2024-05-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0002_remove_carad_car_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='carad',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='realtyad',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
