# Generated by Django 5.0.4 on 2024-04-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0002_rename_photo_url_car_sent_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_customs_cleared',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_mileage',
            field=models.TextField(),
        ),
    ]
