# Generated by Django 5.0.6 on 2024-07-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
