# Generated by Django 4.0.6 on 2024-04-24 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tgapi', '0002_remove_carad_ad_id_remove_carad_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carad',
            name='ad_id',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='carad',
            name='contact_name',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='carad',
            name='contact_phone',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='carad',
            name='currency',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='carad',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='carad',
            name='description',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='carad',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='photos',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='carad',
            name='price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='carad',
            name='title',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='carad',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='photos',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='realtyad',
            name='photos',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='realtyad',
            name='price',
            field=models.IntegerField(default='0'),
        ),
    ]
