# Generated by Django 4.0.6 on 2024-05-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0003_userprofilelink_alter_carad_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilelink',
            old_name='user_id',
            new_name='username',
        ),
    ]
