# Generated by Django 5.0.4 on 2024-04-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0003_alter_car_car_customs_cleared_alter_car_car_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_owners',
            field=models.TextField(),
        ),
    ]
