# Generated by Django 5.0.4 on 2024-07-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
