# Generated by Django 4.0.6 on 2024-04-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0003_carad_ad_id_carad_contact_name_carad_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carad',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jobad',
            name='description',
        ),
        migrations.RemoveField(
            model_name='realtyad',
            name='description',
        ),
        migrations.RemoveField(
            model_name='realtyad',
            name='rooms_number',
        ),
        migrations.AddField(
            model_name='carad',
            name='username_tg',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='jobad',
            name='username_tg',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='realtyad',
            name='username_tg',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
