# Generated by Django 4.0.6 on 2024-05-30 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0004_rename_user_id_userprofilelink_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobad',
            old_name='job_title',
            new_name='job_category',
        ),
    ]
