# Generated by Django 4.0.6 on 2024-05-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0004_remove_carad_description_remove_jobad_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobad',
            name='job_price',
            field=models.IntegerField(default='0'),
        ),
    ]
