# Generated by Django 5.0.4 on 2024-04-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0004_alter_car_car_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='sent_photos',
            field=models.URLField(blank=True, null=True),
        ),
    ]
