# Generated by Django 5.0.4 on 2024-04-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0005_alter_car_sent_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='sent_photos',
        ),
        migrations.AddField(
            model_name='car',
            name='photo_0',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
