# Generated by Django 4.0.6 on 2024-05-02 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0005_alter_jobad_job_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobad',
            old_name='job_conditions',
            new_name='job_description',
        ),
        migrations.RemoveField(
            model_name='jobad',
            name='job_requirements',
        ),
        migrations.RemoveField(
            model_name='jobad',
            name='job_responsibilities',
        ),
    ]
