# Generated by Django 4.0.6 on 2024-05-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0006_rename_job_conditions_jobad_job_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtyad',
            name='realty_commercial_type',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
