# Generated by Django 5.0.4 on 2024-04-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0006_remove_car_sent_photos_car_photo_0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photo_0',
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='car_images/'),
        ),
    ]
