# Generated by Django 4.0.6 on 2024-05-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0007_realtyad_realty_commercial_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtyad',
            name='realty_location',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
