# Generated by Django 5.0.4 on 2024-07-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0007_alter_carad_price_alter_jobad_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carad',
            name='car_price',
        ),
    ]
