# Generated by Django 4.0.6 on 2024-05-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0008_realtyad_realty_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtyad',
            name='realty_commercial_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='realtyad',
            name='realty_contacts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtyad',
            name='realty_currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtyad',
            name='realty_deal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='realtyad',
            name='realty_floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realtyad',
            name='realty_floors_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realtyad',
            name='realty_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtyad',
            name='realty_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtyad',
            name='realty_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realtyad',
            name='realty_rooms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='realtyad',
            name='realty_square',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realtyad',
            name='realty_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
