# Generated by Django 4.0.6 on 2024-05-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0010_alter_carad_ad_id_alter_carad_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtyad',
            name='realty_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
