# Generated by Django 5.0.4 on 2024-04-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0012_remove_car_car_images_car_photo_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='photo_urls',
            new_name='photos',
        ),
    ]
