# Generated by Django 5.0.4 on 2024-04-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0014_alter_car_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
