# Generated by Django 5.0.4 on 2024-04-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0015_alter_car_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
