# Generated by Django 5.0.4 on 2024-04-10 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0019_car_photos_delete_carphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photos',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_photos/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tgapi.car')),
            ],
        ),
    ]
