# Generated by Django 5.0.4 on 2024-04-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0023_alter_car_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date_published',
            field=models.DateTimeField(default='2024-04-12 12:00:00'),
        ),
    ]
