# Generated by Django 5.0.4 on 2024-04-12 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0024_car_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
