# Generated by Django 5.0.4 on 2024-04-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0025_alter_car_date_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_id', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=255)),
                ('job_requirements', models.TextField()),
                ('job_responsibilities', models.TextField()),
                ('job_conditions', models.TextField()),
                ('job_contacts', models.CharField(max_length=255)),
                ('photos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_id', models.CharField(max_length=100)),
                ('realty_deal', models.CharField(max_length=100)),
                ('realty_type', models.CharField(max_length=100)),
                ('realty_square', models.FloatField()),
                ('photos', models.TextField()),
            ],
        ),
    ]
