# Generated by Django 4.0.6 on 2024-04-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0027_remove_car_username_car_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
        migrations.AddField(
            model_name='car',
            name='user_id',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='job',
            name='user_id',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='realty',
            name='user_id',
            field=models.IntegerField(default=2),
        ),
    ]
