# Generated by Django 4.0.6 on 2024-04-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0028_remove_car_user_car_user_id_job_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='realty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
