# Generated by Django 4.0.6 on 2024-04-22 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tgapi', '0029_car_is_active_job_is_active_realty_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='realty',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
